import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Home - Zioun",
    template: "%s | Zioun"
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="https://i.ibb.co.com/jGWVY81/z-1-removebg-preview.png" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
